### ISSUE TITLE
Feature Request: Add user settings to disable a package manager.

### ISSUE THREAD

**Issue by yCodeTech** [faissaloux/vscode-package-manager-intellisense#20]
Could you please add some settings so users can disable/enable the execution and displaying of versions for a particular package manager.

I use the [PHP extension by DEVSENSE](https://marketplace.visualstudio.com/items?itemName=DEVSENSE.phptools-vscode) and auto installs their [Composer extension](https://marketplace.visualstudio.com/items?itemName=DEVSENSE.composer-php-vscode). 

The Composer extension also implements the displaying of installed versions, and with your multi-manager extension installed, those versions are displayed twice. So it would be a great idea to allow users to disable the display for a particular package manager.

I need this extension for npm, and it's the best one I've come across to display installed versions for npm. But with also dealing with Composer and no way to disable it currently, I'm not sure I can use it with the duplicated versions.

**Comment by faissaloux** [comment]
Yeah good point! I'll add this ASAP

Thanks for your suggestion.
